#include <linux/ioctl.h>

//IOCTL CMD

/*
#define IOCTL_GET 0x10
#define IOCTL_SET 0x20
#define IOCTL_STREAMON 0x30
#define IOCTL_STREAMOFF 0x40
#define IOCTL_GRAB 0x50
#define IOCTL_PANTILT 0x60
#define IOCTL_PANTILT_RESEST 0x70
*/

#define CHARDRIVER_IOC_MAGIC 'j'

#define IOCTL_GET _IO(CHARDRIVER_IOC_MAGIC,0x10)
#define IOCTL_SET _IO(CHARDRIVER_IOC_MAGIC,0x20)
#define IOCTL_STREAMON _IO(CHARDRIVER_IOC_MAGIC,0x30)
#define IOCTL_STREAMOFF _IO(CHARDRIVER_IOC_MAGIC,0x40)
#define IOCTL_GRAB _IO(CHARDRIVER_IOC_MAGIC,0x50)
#define IOCTL_PANTILT _IO(CHARDRIVER_IOC_MAGIC,0x60)
#define IOCTL_PANTILT_RESEST _IO(CHARDRIVER_IOC_MAGIC,0x70)


#define CHARDRIVER_IOC_MAXNR 0x70

//Direction camera
#define HAUT 1
#define BAS 2
#define GAUCHE 3
#define DROITE 4
